blank_issues_enabled: true
contact_links:
  - name: Ask more Question
    url: https://t.me/mkikets
    about: You have any questions? You can ask them with blank issue template below, or more personaly on this link>
